import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import { Rubik } from 'next/font/google';
import "@/styles/tailwind.css"
import { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
 
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["arabic", "latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages();
 
  return (
    <html lang={locale} className='dark' style={{colorScheme: 'dark'}} suppressHydrationWarning>
      <body className={`${rubik.variable} font-rubik antialiased`} >
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider attribute={"class"}>
          	{children}
        	</ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}